'use client';

import { useState, FormEvent, ChangeEvent } from 'react';
import { supabase } from '@/config/supabase';

interface FormData {
    full_name: string;
    email: string;
    phone: string;
    organization: string;
    number_of_guests: number;
    special_requirements: string;
    attendance_date: string;
}

interface EventDetails {
    title: string;
    date: string;
    time: string;
    location: string;
    description: string;
    image: string;
}

interface Props {
    onSuccess?: () => void;
    eventDetails: EventDetails;
}

export default function RegistrationForm({ onSuccess, eventDetails }: Props) {
    const [isLoading, setIsLoading] = useState(false);
    const [message, setMessage] = useState({ type: '', text: '' });
    const [form, setForm] = useState<FormData>({
        full_name: '',
        email: '',
        phone: '',
        organization: '',
        number_of_guests: 1,
        special_requirements: '',
        attendance_date: ''
    });
    const [errors, setErrors] = useState<Partial<FormData>>({});

    const validate = (data: FormData) => {
        const errors: Partial<FormData> = {};
        if (!data.full_name.trim()) errors.full_name = 'Name is required';
        if (!data.email.trim()) {
            errors.email = 'Email is required';
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) {
            errors.email = 'Invalid email format';
        }
        if (!data.phone.trim()) errors.phone = 'Phone is required';
        if (!data.attendance_date) errors.attendance_date = 'Date is required';
        return errors;
    };

    const handleChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        const snakeCaseName = name.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
        setForm(prev => ({ ...prev, [snakeCaseName]: value }));
        if (errors[snakeCaseName as keyof FormData]) {
            setErrors(prev => ({ ...prev, [snakeCaseName]: '' }));
        }
        if (message.text) {
            setMessage({ type: '', text: '' });
        }
    };

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        const newErrors = validate(form);
        
        if (Object.keys(newErrors).length > 0) {
            setErrors(newErrors);
            return;
        }

        setIsLoading(true);
        setMessage({ type: '', text: '' });

        try {
            if (!supabase) {
                throw new Error('Supabase client is not initialized');
            }

            // Prepare the form data matching exact column names from Supabase
            const formData = {
                fullname: form.full_name,
                email: form.email,
                phone: form.phone,
                organization: form.organization || null,
                eventtitle: eventDetails.title,
                eventdate: eventDetails.date,
                eventtime: eventDetails.time,
                attendancedate: form.attendance_date,
                numberofguests: parseInt(form.number_of_guests.toString(), 10),
                specialrequirements: form.special_requirements || null,
                status: 'pending'
                // timestamp will be auto-generated by Supabase
            };

            console.log('Submitting registration with data:', formData);

            const { data, error } = await supabase
                .from('registration_form')
                .insert([formData])
                .select()
                .single();

            console.log('Supabase response:', { data, error });

            if (error) {
                console.error('Supabase error:', JSON.stringify(error, null, 2));
                throw new Error(error.message || 'Failed to submit registration');
            }

            if (!data) {
                throw new Error('No data returned from registration');
            }

            setMessage({ type: 'success', text: 'Registration successful! We will contact you shortly.' });
            setForm({
                full_name: '',
                email: '',
                phone: '',
                organization: '',
                number_of_guests: 1,
                special_requirements: '',
                attendance_date: ''
            });
            
            if (onSuccess) {
                onSuccess();
            }
        } catch (error: any) {
            console.error('Registration error:', error);
            let errorMessage = 'Registration failed. Please try again.';
            
            if (error.message) {
                errorMessage = error.message;
                if (error.message.includes('duplicate key')) {
                    errorMessage = 'You have already registered for this event.';
                } else if (error.message.includes('violates foreign key')) {
                    errorMessage = 'Invalid event details provided.';
                }
            }

            setMessage({ 
                type: 'error', 
                text: errorMessage
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto">
            <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4">{eventDetails.title}</h2>
                <div className="bg-gray-50 rounded-lg p-6 space-y-4">
                    <div className="flex items-center gap-2 text-gray-600">
                        <span className="font-medium">Date:</span>
                        <span>{eventDetails.date}</span>
                    </div>
                    <div className="flex items-center gap-2 text-gray-600">
                        <span className="font-medium">Time:</span>
                        <span>{eventDetails.time}</span>
                    </div>
                    <div className="flex items-center gap-2 text-gray-600">
                        <span className="font-medium">Location:</span>
                        <span>{eventDetails.location}</span>
                    </div>
                    <p className="text-gray-600">{eventDetails.description}</p>
                </div>
            </div>
            <form onSubmit={handleSubmit} className="space-y-6 py-8">
                <div className="space-y-4">
                    <div>
                        <label htmlFor="full_name" className="block text-sm font-medium text-gray-700">
                            Full Name *
                        </label>
                        <input
                            type="text"
                            id="full_name"
                            name="full_name"
                            value={form.full_name}
                            onChange={handleChange}
                            className={`mt-1 block w-full rounded-lg border ${
                                errors.full_name ? 'border-red-500' : 'border-gray-300'
                            } px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent`}
                        />
                        {errors.full_name && <p className="mt-1 text-sm text-red-500">{errors.full_name}</p>}
                    </div>

                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <div>
                            <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                                Email *
                            </label>
                            <input
                                type="email"
                                id="email"
                                name="email"
                                value={form.email}
                                onChange={handleChange}
                                className={`mt-1 block w-full rounded-lg border ${
                                    errors.email ? 'border-red-500' : 'border-gray-300'
                                } px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent`}
                            />
                            {errors.email && <p className="mt-1 text-sm text-red-500">{errors.email}</p>}
                        </div>

                        <div>
                            <label htmlFor="phone" className="block text-sm font-medium text-gray-700">
                                Phone *
                            </label>
                            <input
                                type="tel"
                                id="phone"
                                name="phone"
                                value={form.phone}
                                onChange={handleChange}
                                className={`mt-1 block w-full rounded-lg border ${
                                    errors.phone ? 'border-red-500' : 'border-gray-300'
                                } px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent`}
                            />
                            {errors.phone && <p className="mt-1 text-sm text-red-500">{errors.phone}</p>}
                        </div>
                    </div>

                    <div>
                        <label htmlFor="organization" className="block text-sm font-medium text-gray-700">
                            Organization (Optional)
                        </label>
                        <input
                            type="text"
                            id="organization"
                            name="organization"
                            value={form.organization}
                            onChange={handleChange}
                            className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent"
                        />
                    </div>

                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <div>
                            <label htmlFor="attendance_date" className="block text-sm font-medium text-gray-700">
                                Attendance Date *
                            </label>
                            <input
                                type="date"
                                id="attendance_date"
                                name="attendance_date"
                                value={form.attendance_date}
                                onChange={handleChange}
                                min={new Date().toISOString().split('T')[0]}
                                className={`mt-1 block w-full rounded-lg border ${
                                    errors.attendance_date ? 'border-red-500' : 'border-gray-300'
                                } px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent`}
                            />
                            {errors.attendance_date && <p className="mt-1 text-sm text-red-500">{errors.attendance_date}</p>}
                        </div>

                        <div>
                            <label htmlFor="number_of_guests" className="block text-sm font-medium text-gray-700">
                                Number of Guests *
                            </label>
                            <select
                                id="number_of_guests"
                                name="number_of_guests"
                                value={form.number_of_guests}
                                onChange={handleChange}
                                className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent"
                            >
                                {[1, 2, 3, 4, 5].map(num => (
                                    <option key={num} value={num}>
                                        {num} {num === 1 ? 'Guest' : 'Guests'}
                                    </option>
                                ))}
                            </select>
                        </div>
                    </div>

                    <div>
                        <label htmlFor="special_requirements" className="block text-sm font-medium text-gray-700">
                            Special Requirements (Optional)
                        </label>
                        <textarea
                            id="special_requirements"
                            name="special_requirements"
                            value={form.special_requirements}
                            onChange={handleChange}
                            rows={3}
                            className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-2 focus:ring-2 focus:ring-primary focus:border-transparent"
                        />
                    </div>
                </div>

                <button
                    type="submit"
                    disabled={isLoading}
                    className="w-full rounded-lg bg-primary px-4 py-3 text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 disabled:opacity-50 transition-colors"
                >
                    {isLoading ? 'Submitting...' : 'Register'}
                </button>
            </form>
            {message.text && (
                <div className={`p-4 rounded ${
                    message.type === 'success' ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-800'
                }`}>
                    {message.text}
                </div>
            )}
        </div>
    );
}
